language: python
python:
- 3.7
script:
- pip install yapf
- diffs=$(yapf -dr --style=yapf.ini ./thunderbolt)
- if [ -n "$diffs" ]; then exit 1; fi
- python setup.py install
- python -m unittest discover -s ./test/
deploy:
  on:
    tags: true
  provider: pypi
  user: vaaaaanquish
  password:
    secure: l8FZhNKfLHbxrRbFCSU6nLz6ChtPjcQ5G/ELRnIZnF5x6oxSV+MS/zfmGpM/NDTkAY87k6Zw917ZmE79E5xxU4+LrhACY84AAFubau+YmtV/PoYZnRaIcN/vZMA0LXRp+TTbqBK233HN+SkfSM0vUFECjVDYfZcIP3BJSH7LZRBHMIPqso3Bt9v2v7OuNbUckEmMe9dHFYcSRAuUmRkJ4IY72vYHKUiePT+ZzCifESeQPMPu0iymwlio8SU/gcbD3qyfYjx/KKFbMotvXCFiM2TtqyxDcmaOSxyzjoqWgyD8DibRLqHNJEIZCkIHM4LsqvjDzgU4bvXts6VNZcBo+8I6HIHxNiegXndxK+UBh1xgY/GjnwoRR9Bzg0PSaFM8M97QPc7u+zqbgMgw5IM3SFOz/xaqPi0oZASupBGEmGeixvreikmbQiRmDgCY5Jcb/Z+anlF1MeAT9iVryo+zuIZanZeFTvSgEMsqxmRbW8ONfehKvNLFu8WBsYnJBSgc+/TlPFlKOXeq+6amgwH9YvQS0qFBWL/y6IQ+3EZAWZXljKBYq4Sn0USeUan/y9IdG0F5amVdabTxOZeSXg24rP+2MDn5zzVq/PTl5Hi09sJiqtMMO7yYSoXPKnr6BOqMrTgJjRzENm7rj3KxBT746xWGSqSlkwiCLrtME30ayYI=
