language: python
python:
    - 3.7
script:
    - pip install yapf
    - diffs=$(yapf -dr --style=yapf.ini ./thunderbolt)
    - if [ -n "$diffs" ]; then exit 1; fi
    - python setup.py install
    - cd test
    - python -m unittest discover -s ./
